version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-urbanhost
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: urbanhost
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
